### ISSUE TITLE
apps/esbuild-example doesn't build standalone

### ISSUE THREAD

**Issue by TheSisb** [facebook/stylex#445]
### Describe the issue

When trying to implement the esbuild-example in my own app, I get the following build error:

```sh
npm run build

> styling@1.0.0 build
> node scripts/build.mjs

✘ [ERROR] /Users/sisber/styling/src/App.tsx: Only static values are allowed inside of a stylex.create() call. [plugin esbuild-plugin-stylex]

    node_modules/@stylexjs/babel-plugin/lib/index.js:4235:12:
      4235 │       throw new Error(messages_1.NON_STATIC_VALUE);
           ╵             ^

    at transformStyleXCreate (/Users/sisber/styling/node_modules/@stylexjs/babel-plugin/lib/index.js:4235:13)
    at CallExpression (/Users/sisber/styling/node_modules/@stylexjs/babel-plugin/lib/index.js:5682:15)
    at NodePath._call (/Users/sisber/styling/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/sisber/styling/node_modules/@babel/traverse/lib/path/context.js:36:17)
```

### Expected behavior

It should build correctly.

### Steps to reproduce

- Copy the `apps/esbuild-example` folder into a new folder, outside of this monorepo
- Run `npm i`
- Run `npm run build`

### Additional comments

This makes it difficult to adopt stylex in an esbuild environment.

**Comment by nedjulius** [comment]
try to run `npm install @stylex/open-props`
