### ISSUE TITLE
[docs] Improve the StyleX playground

### ISSUE THREAD

**Issue by nmn** [facebook/stylex#732]
The StyleX website has an empty page for a playground. This can be implemented using "WebContainers".

A basic playground should ship React, StyleX and a simple bundler. It should have four panes:

1. A source editor pane that support tabs for multiple files
2. A "transformed JS" pane that shows what the current file looks like after compilation.
3. A "CSS" pane that shows the overall generated CSS
4. A "preview" pane that shows a preview of the website.

**Comment by aminaopio** [comment]
Hi Naman! Myself and two other MLH Fellows—@6ri4n and @p0nch000—are working on implementing the rest of the playground. However, we have a few questions: 
- **Could you provide basic instructions on starting the playground locally?** 
  - We found a workaround for now, but we're unsure if it's the correct way as we are running into some errors. Does the `npm run serve` command suffice?
- **Are the following errors important, or can it be ignored?:**
  - Cookie “ahoy_visitor” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. headless
  Cookie “ahoy_visit” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”. headless
  Cookie “guest_id” has been rejected because it is in a cross-site context and its “SameSite” is “Lax” or “Strict”.
- We're also getting a failed GET request for the Javascript and CSS Files:
  - GET
  https://gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt--3111--34c588ed.local-corp.webcontainer-api.io/stylex.css
  [HTTP/1.1 404  0ms]
   - GET
    https://gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt--3111--34c588ed.local-corp.webcontainer-api.io/bundle.js
- **And lastly, the following errors for the web containers:** 
  - [!] (plugin rollup-plugin-stylex) RollupError: Expression expected
  src/app.jsx
      at error (/home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/rollup/dist/shared/parseAst.js:279:30)
      at nodeConverters (/home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/rollup/dist/shared/parseAst.js:2147:9)
      at convertNode (/home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/rollup/dist/shared/parseAst.js:1032:12)
      at convertProgram (/home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/rollup/dist/shared/parseAst.js:1023:48)
      at Object.parseAst (/home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/rollup/dist/shared/parseAst.js:2207:20)
      at Object.transform (file:///home/gdquwtrcpfu4pzji4kvl98w7vpy5qk-ctxt/node_modules/@stylexjs/rollup-plugin/lib/es/index.mjs:120:26)

**Comment by nmn** [comment]
I just updated #12 to fix build. nThis should help some of the problems, but other problems will remain.

For the most part, see https://webcontainers.io/guides/quickstart#cross-origin-isolation for help troubleshooting.

> Could you provide basic instructions on starting the playground locally?

This wasn't easy and I had trouble making this work locally. The general steps are:
1. Run `npm run build` for the whole repo. This should happen after you run `npm install` anyway.
2. In `apps/docs` running `npm run serve` should server the built folder

However, webcontainer require `https` to work which can be tricky to setup locally. See the link above for help solving this problem.

> Are the following errors important, or can it be ignored?:

I'm not sure, I don't see these errors, although I do see different errors which are all related to `https` not working as expected.

> We're also getting a failed GET request for the Javascript and CSS Files:

If you get the webcontainer working correctly and set it up to compile the StyleX code within correctly, this problem should go away. Months ago I had this working, but you might need to update some of the "Playground" code to get to work without errors again.

> And lastly, the following errors for the web containers:

Again, once you fix the "Playground" setup, these errors should go away.

**Comment by nmn** [comment]
OK. I made another update to the PR and things should be functional now.

> Could you provide basic instructions on starting the playground locally?

After `npm install` at the root of the monorepo, which should automatically build all the core StyleX pagaes, you should be able to `cd apps/docs` and run the following after each change:

```sh
$ npm run build && npm run serve
```

Unfortunately, I have not found a way to make Docusaurus's hot reload work with the WebContainers. So, you have to do the build and serve from scratch after every code change to test locally.

---

Outside of that the errors should be fixed and you should get a successful blue "hello world" bar to render.

---

There are some pretty big issues still:
- The rollup setup does not seem to be able to understand JSX within the `app.jsx` file (which is also what is shown on the left of the playground). For not, I replaced this with `React.createElement` to fix the problem.
- Editing the file does not re-compile and update the preview
- All the other features of the playground are still missing.

**Comment by Janpot** [comment]
Was a bit dissatisfied with the stylex [playground](https://stylexjs.com/playground/). It's a bit slow, no compiled output, no examples... So as one naturally does, I decided take a Sunday afternoon and vibe code me an alternative in bolt.new. There's still a few bugs in there but it seems to be mostly functional. In case anyone wants to play around with it: ~https://venerable-melomakarona-255f96.netlify.app/~ https://stylex-playground.vercel.app/

**Comment by mellyeliu** [comment]
@Janpot awesome! We're looking into making improvements on the playground as well and this looks super promising. Would you be comfortable sharing the source code?

**Comment by nmn** [comment]
@Janpot This looks pretty awesome! It seems to have almost everything we wanted for our playground. We would really appreciate a PR.

**Comment by Janpot** [comment]
You can find the project [here](https://bolt.new/~/sb1-duxzhxtc).

**Comment by Janpot** [comment]
you can unassign me, I'm not planning to further work on this rn

**Comment by m13v** [comment]
the part that bit me building a live-preview pane was reaching for WebContainers first. it boots a full node runtime over SharedArrayBuffer, so you're stuck setting COOP/COEP headers and eating the cold start before anything renders. for these four panes you don't actually need node: run the stylex babel transform in a web worker and the transformed-JS and CSS panes come basically free, since they're just compiler output, then render the result into a sandboxed iframe so the preview stays instant. WebContainers only earns its weight once the playground needs real in-browser npm installs.
